unique_ids:
  assets:
    standard-page.html: UL23AFKANHLF47VVHZUOE4R5KXHXQJ3E
    theme.css: VICJXZ7FPC55ES3OXD4XO6YTIOIJH2IY
  forms:
    ArticleEdit: '1782739332726685042508988.9851'
    Homepage: F5E2L3CNIU3XZLRV7FKV35CCUULDUX6X
  modules: {}
  scripts: {}
  server_modules: {}
